# Generated by Django 5.1.2 on 2024-10-18 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_statuses_tags_tasks_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Status',
        ),
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
